### ISSUE TITLE
Incompatibility with python 3.8

### ISSUE THREAD

**Issue by bognabylicka** [openvinotoolkit/nncf_pytorch#134]
I noticed incompatibility of NNCF with python 3.8.
The problem occurs during installation of one of the dependencies of NNCF and it seems to be caused by the fact that platform.linux_distribution was removed in Python 3.8:

```Collecting matplotlib==.0.3
  ​Downloading matplotlib-3.0.3.tar.gz (36.6 B)
    ​ERROR: Command errored out with exit status :
     ​command: /opt/home/k8sworker/cibuilds/impt/nncf_for_digits-9/src/model_templates/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0zqb86kn/matplotlib/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0zqb86kn/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-0zqb86kn/matplotlib/pip-egg-info
        ​cwd: /tmp/pip-install-0zqb86kn/matplotlb/
    ​Complete output (51 line):
    ​Traceback (most recent call last)
      ​File "<string>", line 1, in <module
      ​File "/tmp/pip-install-0zqb86kn/matplotlib/setup.py", line 225, in <module>
       ​msg = pkg.install_help_msg(
      ​File "/tmp/pip-install-0zqb86kn/matplotlib/setupext.py", line 650, in install_help_msg
       ​release = platform.linux_distribution()[0].lowe()
    ​AttributeError: module 'platform' has no attribute 'linux_distributin'```

**Comment by AlexKoff88** [comment]
@asenina, can you please take a look and fix it when you are free from the current task?

**Comment by asenina** [comment]
@AlexKoff88 Ok

**Comment by jpowie01** [comment]
What's the status of this issue? It looks that NNCF uses too old version of Matplotlib (3.0.3).

Matplotlib supports Python 3.8 starting with version 2.2.5: https://github.com/matplotlib/matplotlib/releases/tag/v2.2.5
