### ISSUE TITLE
KeyError: 'quantization_range_init_args'

### ISSUE THREAD

**Issue by adamantboy** [openvinotoolkit/nncf_pytorch#153]
This error occurs when i quantize FP32 pretrained model，is this a bug?
Traceback (most recent call last):
  File "/home/mechmind/projects/nncf_pytorch/nncf/quantization/algo.py", line 961, in init_range
    range_init_args = self.quantization_config.get_extra_struct(QuantizationRangeInitArgs)
  File "/home/mechmind/projects/nncf_pytorch/nncf/config.py", line 56, in get_extra_struct
    return self.__nncf_extra_structs[struct_cls.get_id()]
KeyError: 'quantization_range_init_args'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 381, in <module>
    main(sys.argv[1:])
  File "main.py", line 81, in main
    start_worker(main_worker, config)
  File "/home/mechmind/projects/nncf_pytorch/examples/common/execution.py", line 99, in start_worker
    main_worker(current_gpu=config.gpu_id, config=config)
  File "main.py", line 152, in main_worker
    compression_ctrl, net = create_model(config, resuming_model_state_dict)
  File "main.py", line 239, in create_model
    compression_ctrl, compressed_model = create_compressed_model(ssd_net, config.nncf_config, resuming_model_sd)
  File "/home/mechmind/projects/nncf_pytorch/nncf/model_creation.py", line 126, in create_compressed_model
    compression_ctrl = compressed_model.commit_compression_changes()
  File "/home/mechmind/projects/nncf_pytorch/nncf/nncf_network.py", line 416, in commit_compression_changes
    return self._builders[0].build_controller(self)
  File "/home/mechmind/projects/nncf_pytorch/nncf/quantization/algo.py", line 200, in build_controller
    self._hw_precision_constraints)
  File "/home/mechmind/projects/nncf_pytorch/nncf/quantization/algo.py", line 816, in __init__
    self.initialize_quantizer_params()
  File "/home/mechmind/projects/nncf_pytorch/nncf/quantization/algo.py", line 893, in initialize_quantizer_params
    self.init_range()
  File "/home/mechmind/projects/nncf_pytorch/nncf/quantization/algo.py", line 964, in init_range
    'Should run range initialization as specified via config,'
ValueError: Should run range initialization as specified via config,but the initializing data loader is not provided as an extra struct. Refer to `NNCFConfig.register_extra_structs` and the `QuantizationRangeInitArgs` class

**Comment by vshampor** [comment]
@adamantboy please post exact command lines you used to launch the NNCF sample and the NNCF config file.

**Comment by adamantboy** [comment]
> @adamantboy please post exact command lines you used to launch the NNCF sample and the NNCF config file.

I solved this problem.
